### ISSUE TITLE
Cannot get "Everything" devices to publish to HA

### ISSUE THREAD

**Issue by moofur** [xAPPO/MQTT#18]
I installed the App and Driver, set up the User App, and got it connected to my broker (verified w/ MQTT Explorer). I followed the instructions to get my HE devices published so I could pick them up in HA (https://github.com/xAPPO/MQTT#c-enable-automatic-discovery-of-he-devices-by-other-controllers-eg-ha-using-home-assistant-discovery-protocol).

When I select individual devices from the individual capability lists, I can see the messages in MQTT Explorer and in Home Assistant. However, when I select something from the "Everything" list, I get nothing. I do see the devices I've selected in the homie topics, so I know it's publishing, just not for HA.

When I have a device selected under "Everything", I do see one error in the logs:
`java.lang.NullPointerException: Cannot get property 'displayName' on null object on line 2210 (method updated)`
![image](https://github.com/xAPPO/MQTT/assets/22972834/1712d91e-690c-45df-ae27-9eace8fc5e37)

Line 2210 in the app code is trying to parse `dev.displayName`.
![image](https://github.com/xAPPO/MQTT/assets/22972834/6129db7c-e9df-4aec-974b-1b4bba1cd33d)

I'm assuming there is additional information you'll want, or something else you'll want me to try, for troubleshooting. Please let me know what and I'll be happy to do so. I would love to see this working.

**Comment by GledholtHall** [comment]
From memory this was not working correctly in this version.  ‘Everything’ should be avoided and instead enable in the individual sections instead.
OR
Use latest beta 3e instead - it’s in another repository. If you want to try this’s then PM me directly via the Hubitat community and I will send you a link.  You need to do it this way as I need an agreement to the more restrictive terms within the temporary licence that 3e has.

**Comment by moofur** [comment]
I've since ended up moving all of my Z-Wave stuff over to Home Assistant, so this is no longer an issue for me. I did end up getting things published to HA by using the individual section selectors.
