### ISSUE TITLE
HA state stream discovery issue

### ISSUE THREAD

**Issue by ajagnanan** [xAPPO/MQTT#3]
Not sure how to go about finding what the issue is. I have 19 devices in home assistant, but the app only discovers 10 of those devices every time. If I manually subscribe to <statestream>/binary_sensor/+/friendly_name, I do get all the devices. It might be related to the "pacing" I saw in the code, but not sure. Thanks for checking.

**Comment by Gledholt** [comment]
What device types are the 9 that are not discovered and in what statestream topic hierarchy do they advertise, are you saying they are all binary_sensors ?  

Many types are not supported yet  e.g. things like statestream/remote/..,  statestream/climate/.., statestream/sun/.., statestream/zone/..  statestream/media_player/.. statestream/persistent_notification/.. and others  are not discovered

Do they all have a device_class topic reported to MQTT  ?

If they are in binary_sensors please send me a topic expansion of some of them and I'll see why +/binary_sensor/+/friendly_name does not return them - are there any log errors or warnings ?

**Comment by ajagnanan** [comment]
Yea, they are all binary_sensor (just door/window contact sensors). Hmm how would I get the topic expansions? I can do that when home. I did add them manually and its working.

**Comment by Gledholt** [comment]
![image](https://user-images.githubusercontent.com/55451838/74597316-68dd5780-5055-11ea-92f1-a75ccda8fcc6.png)


Use something like the MQTT Explorer app and screegrab a problem device within binary_sensors

**Comment by ajagnanan** [comment]
This one did not work
![image](https://user-images.githubusercontent.com/752895/74598303-48090800-503d-11ea-86da-f746bd13adc0.png)

This one worked
![image](https://user-images.githubusercontent.com/752895/74598318-91f1ee00-503d-11ea-8a5d-5de92b44ff31.png)


The look the same

**Comment by xAPPO** [comment]
Yes they look the same..  I will manually create the first one and see what happens.

**Comment by xAPPO** [comment]
This device is discovered for me
![image](https://user-images.githubusercontent.com/875211/74971747-807f5c00-5418-11ea-9566-e62c8b27cd63.png)
![image](https://user-images.githubusercontent.com/875211/74971783-8d9c4b00-5418-11ea-98a4-4ba96c99b1cc.png)

**Comment by ajagnanan** [comment]
I tested this again and it worked. Not sure what happened the first time. Thanks for checking.
